#!/usr/bin/env python3
"""
Package a skill for cross-platform distribution.

Creates a complete package with instruction files for all platforms,
plus a sync script for ongoing maintenance.

Usage:
    python package_cross_platform.py <skill-dir> [--output <dir>]
    
Examples:
    python package_cross_platform.py ./my-skill
    python package_cross_platform.py ./my-skill --output ./dist
"""

import argparse
import shutil
import sys
from pathlib import Path
from datetime import datetime

# Import conversion functions from sibling script
from convert_skill import convert_skill, extract_frontmatter


SYNC_SCRIPT = '''#!/bin/bash
# Sync instruction files from canonical source
# Generated by cross-platform-skill

CANONICAL="${1:-CLAUDE.md}"

if [ ! -f "$CANONICAL" ]; then
    echo "Error: Canonical file not found: $CANONICAL"
    exit 1
fi

echo "Syncing from $CANONICAL..."

case "$CANONICAL" in
    CLAUDE.md)
        TARGETS="AGENTS.md GEMINI.md"
        ;;
    AGENTS.md)
        TARGETS="CLAUDE.md GEMINI.md"
        ;;
    GEMINI.md)
        TARGETS="CLAUDE.md AGENTS.md"
        ;;
    *)
        echo "Warning: Unknown canonical file. Syncing to all platforms."
        TARGETS="CLAUDE.md AGENTS.md GEMINI.md"
        ;;
esac

for target in $TARGETS; do
    if [ "$target" != "$CANONICAL" ]; then
        echo "  -> $target"
        cp "$CANONICAL" "$target"
    fi
done

echo "Done!"
'''


README_TEMPLATE = '''# {name}

{description}

## Cross-Platform Compatibility

This skill works with multiple AI coding assistants:

- **Claude Code** - Use `CLAUDE.md`
- **Codex CLI** - Use `AGENTS.md`  
- **Gemini CLI** - Use `GEMINI.md`

## Installation

### Claude Code
Copy `CLAUDE.md` to your project root or `~/.claude/CLAUDE.md` for global use.

### Codex CLI
Copy `AGENTS.md` to your project root or `~/.codex/AGENTS.md` for global use.

### Gemini CLI
Copy `GEMINI.md` to your project root or `~/.gemini/GEMINI.md` for global use.

## Keeping Files in Sync

If you modify the instructions, run the sync script to update all platform files:

```bash
./sync.sh CLAUDE.md  # Use CLAUDE.md as the source
```

Or set up symlinks for automatic sync:

```bash
ln -sf CLAUDE.md AGENTS.md
ln -sf CLAUDE.md GEMINI.md
```

## Contents

- `CLAUDE.md` - Instructions for Claude Code
- `AGENTS.md` - Instructions for Codex CLI
- `GEMINI.md` - Instructions for Gemini CLI
- `sync.sh` - Script to sync files after edits
{extra_contents}

---
Generated on {date} by cross-platform-skill
'''


def package_skill(skill_dir: Path, output_dir: Path) -> Path:
    """Package a skill directory for cross-platform distribution."""
    skill_dir = skill_dir.resolve()
    
    # Find the main skill file
    skill_file = skill_dir / 'SKILL.md'
    claude_file = skill_dir / 'CLAUDE.md'
    
    if skill_file.exists():
        source_file = skill_file
    elif claude_file.exists():
        source_file = claude_file
    else:
        print(f"Error: No SKILL.md or CLAUDE.md found in {skill_dir}", file=sys.stderr)
        sys.exit(1)
    
    # Extract skill metadata
    content = source_file.read_text()
    frontmatter, body = extract_frontmatter(content)
    skill_name = frontmatter.get('name', skill_dir.name)
    description = frontmatter.get('description', 'A cross-platform AI coding skill')
    
    # Create output directory
    package_dir = output_dir / skill_name
    package_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Packaging skill: {skill_name}")
    print(f"Output directory: {package_dir}")
    print()
    
    # Convert instruction files
    print("Generating platform instruction files...")
    convert_skill(source_file, package_dir)
    
    # Copy additional resources
    extra_contents = []
    
    for subdir in ['scripts', 'references', 'assets']:
        src = skill_dir / subdir
        if src.exists() and src.is_dir():
            dst = package_dir / subdir
            shutil.copytree(src, dst, dirs_exist_ok=True)
            print(f"  Copied: {subdir}/")
            extra_contents.append(f"- `{subdir}/` - {subdir.title()} and resources")
    
    # Create sync script
    sync_path = package_dir / 'sync.sh'
    sync_path.write_text(SYNC_SCRIPT)
    sync_path.chmod(0o755)
    print(f"  Created: sync.sh")
    
    # Create README
    readme_path = package_dir / 'README.md'
    readme_content = README_TEMPLATE.format(
        name=skill_name,
        description=description,
        extra_contents='\n'.join(extra_contents) if extra_contents else '',
        date=datetime.now().strftime('%Y-%m-%d')
    )
    readme_path.write_text(readme_content)
    print(f"  Created: README.md")
    
    print()
    print(f"Package created: {package_dir}")
    
    return package_dir


def main():
    parser = argparse.ArgumentParser(
        description='Package a skill for cross-platform distribution'
    )
    parser.add_argument(
        'skill_dir',
        type=Path,
        help='Directory containing the skill (with SKILL.md or CLAUDE.md)'
    )
    parser.add_argument(
        '--output', '-o',
        type=Path,
        default=Path('.'),
        help='Output directory for the package (default: current directory)'
    )
    
    args = parser.parse_args()
    
    if not args.skill_dir.exists():
        print(f"Error: Skill directory not found: {args.skill_dir}", file=sys.stderr)
        sys.exit(1)
    
    package_dir = package_skill(args.skill_dir, args.output)
    
    print()
    print("Next steps:")
    print(f"  1. Review the generated files in {package_dir}")
    print(f"  2. Test with each platform")
    print(f"  3. Share the package with users")


if __name__ == '__main__':
    main()
