#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='vim';

# Anaconda
# export PATH="/Users/$USER/anaconda3/bin:$PATH"

# Poetry
export PATH="$HOME/.local/bin:$PATH"

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# jdk11
export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
export JAVA_HOME=$(/usr/libexec/java_home)
export OPENAI_BASE_URL=https://e2-demo-field-eng.cloud.databricks.com/serving-endpoints
